"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "hi" | "ta" | "te" | "bn"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Inline translations to avoid import issues
const translations: Record<Language, any> = {
  en: {
    common: {
      language: "Language",
      logout: "Logout",
      loading: "Loading...",
      error: "Error",
      success: "Success",
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      close: "Close",
      back: "Back",
    },
    navbar: {
      liveClasses: "Live Classes",
      schedule: "Schedule",
      notes: "Notes",
      aiAssistant: "AI Study Buddy",
      myLearning: "My Learning Adventure",
    },
    student: {
      dashboard: "Student Dashboard",
      mySchedule: "My Schedule",
      liveClasses: "Live Classes",
      notes: "Study Materials",
      assignments: "Assignments",
      joinClass: "Join Class",
      upcomingClasses: "Upcoming Classes",
      studyMaterials: "Study Materials",
      classNotes: "Class Notes",
      referenceBooks: "Reference Books",
      welcomeBack: "Welcome back",
      levelStudent: "Level {level} Student",
      currentLevel: "Current Level",
      totalXP: "Total XP",
      badgesEarned: "Badges Earned",
      currentStreak: "Current Streak",
      levelProgress: "Level Progress",
      complete: "Complete!",
      overview: "Overview",
      badges: "Badges",
      goals: "Goals",
      leaderboard: "Leaderboard",
      recentAdventures: "Recent Adventures",
      weeklyPerformance: "Weekly Performance",
      myBadgeCollection: "My Badge Collection",
      myLearningGoals: "My Learning Goals",
      classChampions: "Class Champions",
      attendance: "Attendance",
      homework: "Homework",
      behavior: "Behavior",
      participation: "Participation",
      progress: "Progress",
      completedMathHomework: "Completed math homework",
      perfectAttendance: "Perfect attendance",
      helpedClassmate: "Helped classmate",
      perfectAttendanceBadge: "Perfect Attendance",
      mathWizard: "Math Wizard",
      helperHero: "Helper Hero",
      readBooks: "Read 5 books",
      improveHandwriting: "Improve handwriting",
    },
    ai: {
      studyBuddy: "AI Study Buddy",
      askQuestion: "Ask me anything about your studies!",
      typing: "Study Buddy is thinking...",
      placeholder: "Ask a question...",
      sendMessage: "Send",
    },
    schedule: {
      mySchedule: "My Schedule",
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      sunday: "Sunday",
      time: "Time",
      subject: "Subject",
      teacher: "Teacher",
      room: "Room",
    },
    materials: {
      studyMaterials: "Study Materials",
      classNotes: "Class Notes",
      assignments: "Assignments",
      referenceBooks: "Reference Books",
      uploadDate: "Upload Date",
      downloadFile: "Download",
      previewFile: "Preview",
      noMaterials: "No materials available yet",
    },
  },
  hi: {
    common: {
      language: "भाषा",
      logout: "लॉगआउट",
      loading: "लोड हो रहा है...",
      error: "त्रुटि",
      success: "सफल",
      save: "सहेजें",
      cancel: "रद्द करें",
      delete: "हटाएं",
      edit: "संपादित करें",
      add: "जोड़ें",
      close: "बंद करें",
      back: "वापस",
    },
    navbar: {
      liveClasses: "लाइव क्लास",
      schedule: "शेड्यूल",
      notes: "नोट्स",
      aiAssistant: "AI अध्ययन सहायक",
      myLearning: "मेरा सीखने का रोमांच",
    },
    student: {
      dashboard: "छात्र डैशबोर्ड",
      mySchedule: "मेरा शेड्यूल",
      liveClasses: "लाइव क्लास",
      notes: "अध्ययन सामग्री",
      assignments: "असाइनमेंट",
      joinClass: "क्लास में शामिल हों",
      upcomingClasses: "आने वाली क्लासें",
      studyMaterials: "अध्ययन सामग्री",
      classNotes: "कक्षा नोट्स",
      referenceBooks: "संदर्भ पुस्तकें",
      welcomeBack: "वापस स्वागत है",
      levelStudent: "स्तर {level} छात्र",
      currentLevel: "वर्तमान स्तर",
      totalXP: "कुल XP",
      badgesEarned: "अर्जित बैज",
      currentStreak: "वर्तमान स्ट्रीक",
      levelProgress: "स्तर प्रगति",
      complete: "पूर्ण!",
      overview: "अवलोकन",
      badges: "बैज",
      goals: "लक्ष्य",
      leaderboard: "लीडरबोर्ड",
      recentAdventures: "हाल के रोमांच",
      weeklyPerformance: "साप्ताहिक प्रदर्शन",
      myBadgeCollection: "मेरा बैज संग्रह",
      myLearningGoals: "मेरे सीखने के लक्ष्य",
      classChampions: "कक्षा चैंपियन",
      attendance: "उपस्थिति",
      homework: "होमवर्क",
      behavior: "व्यवहार",
      participation: "भागीदारी",
      progress: "प्रगति",
      completedMathHomework: "गणित का होमवर्क पूरा किया",
      perfectAttendance: "पूर्ण उपस्थिति",
      helpedClassmate: "सहपाठी की मदद की",
      perfectAttendanceBadge: "पूर्ण उपस्थिति",
      mathWizard: "गणित जादूगर",
      helperHero: "सहायक हीरो",
      readBooks: "5 किताबें पढ़ें",
      improveHandwriting: "लिखावट सुधारें",
    },
    ai: {
      studyBuddy: "AI अध्ययन सहायक",
      askQuestion: "अपनी पढ़ाई के बारे में कुछ भी पूछें!",
      typing: "अध्ययन सहायक सोच रहा है...",
      placeholder: "एक सवाल पूछें...",
      sendMessage: "भेजें",
    },
    schedule: {
      mySchedule: "मेरा शेड्यूल",
      monday: "सोमवार",
      tuesday: "मंगलवार",
      wednesday: "बुधवार",
      thursday: "गुरुवार",
      friday: "शुक्रवार",
      saturday: "शनिवार",
      sunday: "रविवार",
      time: "समय",
      subject: "विषय",
      teacher: "शिक्षक",
      room: "कक्ष",
    },
    materials: {
      studyMaterials: "अध्ययन सामग्री",
      classNotes: "कक्षा नोट्स",
      assignments: "असाइनमेंट",
      referenceBooks: "संदर्भ पुस्तकें",
      uploadDate: "अपलोड की तारीख",
      downloadFile: "डाउनलोड",
      previewFile: "पूर्वावलोकन",
      noMaterials: "अभी कोई सामग्री उपलब्ध नहीं है",
    },
  },
  ta: {
    common: {
      language: "மொழி",
      logout: "வெளியேறு",
      loading: "ஏற்றுகிறது...",
      error: "பிழை",
      success: "வெற்றி",
      save: "சேமிக்கவும்",
      cancel: "ரद்து செய்யவும்",
      delete: "நீக்கவும்",
      edit: "திருத்தவும்",
      add: "சேர்க்கவும்",
      close: "மூடவும்",
      back: "பின்னால்",
    },
    navbar: {
      liveClasses: "நேரடி வகுப்புகள்",
      schedule: "அட்டவணை",
      notes: "குறிப்புகள்",
      aiAssistant: "AI படிப்பு துணை",
      myLearning: "என் கற்றல் சாகசம்",
    },
    student: {
      dashboard: "மாணவர் டாஷ்போர்ட்",
      mySchedule: "என் அட்டவணை",
      liveClasses: "நேரடி வகுப்புகள்",
      notes: "ஆய்வு பொருட்கள்",
      assignments: "பணிகள்",
      joinClass: "வகுப்பில் சேரவும்",
      upcomingClasses: "வரவிருக்கும் வகுப்புகள்",
      studyMaterials: "ஆய்வு பொருட்கள்",
      classNotes: "வகுப்பு குறிப்புகள்",
      referenceBooks: "குறிப்பு புத்தகங்கள்",
      welcomeBack: "மீண்டும் வரவேற்கிறோம்",
      levelStudent: "நிலை {level} மாணவர்",
      currentLevel: "தற்போதைய நிலை",
      totalXP: "மொத்த XP",
      badgesEarned: "பெற்ற பேட்ஜ்கள்",
      currentStreak: "தற்போதைய தொடர்",
      levelProgress: "நிலை முன்னேற்றம்",
      complete: "முழுமை!",
      overview: "கண்ணோட்டம்",
      badges: "பேட்ஜ்கள்",
      goals: "இலக்குகள்",
      leaderboard: "தலைமை பலகை",
      recentAdventures: "சமீபத்திய சாகசங்கள்",
      weeklyPerformance: "வாராந்திர செயல்திறன்",
      myBadgeCollection: "என் பேட்ஜ் சேகரிப்பு",
      myLearningGoals: "என் கற்றல் இலக்குகள்",
      classChampions: "வகுப்பு சாம்பியன்கள்",
      attendance: "வருகை",
      homework: "வீட்டுப்பாடம்",
      behavior: "நடத்தை",
      participation: "பங்கேற்பு",
      progress: "முன்னேற்றம்",
      completedMathHomework: "கணித வீட்டுப்பாடம் முடித்தது",
      perfectAttendance: "சரியான வருகை",
      helpedClassmate: "வகுப்பு தோழருக்கு உதவியது",
      perfectAttendanceBadge: "சரியான வருகை",
      mathWizard: "கணித மந்திரவாதி",
      helperHero: "உதவி ஹீரோ",
      readBooks: "5 புத்தகங்கள் படிக்கவும்",
      improveHandwriting: "கையெழுத்தை மேம்படுத்தவும்",
    },
    ai: {
      studyBuddy: "AI படிப்பு துணை",
      askQuestion: "உங்கள் பாடங்களைப் பற்றி எதையும் கேளுங்கள்!",
      typing: "AI துணை சிந்தித்துக் கொண்டிருக்கிறது...",
      placeholder: "ஒரு கேள்வி கேளுங்கள்...",
      sendMessage: "அனுப்பு",
    },
    schedule: {
      mySchedule: "என் அட்டவணை",
      monday: "திங்கட்கிழமை",
      tuesday: "செவ்வாய்கிழமை",
      wednesday: "புதன்கிழமை",
      thursday: "வியாழக்கிழமை",
      friday: "வெள்ளிக்கிழமை",
      saturday: "சனிக்கிழமை",
      sunday: "ஞாயிற்றுக்கிழமை",
      time: "நேரம்",
      subject: "பொருள்",
      teacher: "ஆசிரியர்",
      room: "அறை",
    },
    materials: {
      studyMaterials: "ஆய்வு பொருட்கள்",
      classNotes: "வகுப்பு குறிப்புகள்",
      assignments: "பணிகள்",
      referenceBooks: "குறிப்பு புத்தகங்கள்",
      uploadDate: "பதிவேற்றிய தேதி",
      downloadFile: "பதிவிறக்கம்",
      previewFile: "முன்னோட்டம்",
      noMaterials: "இதுவரை பொருட்கள் எதுவும் கிடைக்கவில்லை",
    },
  },
  te: {
    common: {
      language: "భాష",
      logout: "లాగ్ అవుట్",
      loading: "లోడ్ చేస్తోంది...",
      error: "లోపం",
      success: "విజయం",
      save: "సేవ్ చేయండి",
      cancel: "రద్దు చేయండి",
      delete: "తొలగించండి",
      edit: "సవరించండి",
      add: "జోడించండి",
      close: "ఓపెన్ చేయండి",
      back: "వెనుకకు",
    },
    navbar: {
      liveClasses: "లైవ్ క్లాసులు",
      schedule: "షెడ్యూల్",
      notes: "నోట్‌లు",
      aiAssistant: "AI అధ్యయన సహాయక",
      myLearning: "నా నేర్పు సాహసం",
    },
    student: {
      dashboard: "విద్యార్థి డ్యాష్‌బోర్డ్",
      mySchedule: "నా షెడ్యూల్",
      liveClasses: "లైవ్ క్లాసులు",
      notes: "అధ్యయన సామగ్రి",
      assignments: "కార్యనిర్దేశనాలు",
      joinClass: "క్లాసులో చేరండి",
      upcomingClasses: "రానున్న కలాసులు",
      studyMaterials: "అధ్యయన సామగ్రి",
      classNotes: "క్లాస్ నోట్‌లు",
      referenceBooks: "సూచన పుస్తకాలు",
      welcomeBack: "తిరిగి స్వాగతం",
      levelStudent: "స్థాయి {level} విద్యార్థి",
      currentLevel: "ప్రస్తుత స్థాయి",
      totalXP: "మొత్తం XP",
      badgesEarned: "సంపాదించిన బ్యాడ్జ్‌లు",
      currentStreak: "ప్రస్తుత స్ట్రీక్",
      levelProgress: "స్థాయి పురోగతి",
      complete: "పూర్తి!",
      overview: "అవలోకనం",
      badges: "బ్యాడ్జ్‌లు",
      goals: "లక్ష్యాలు",
      leaderboard: "లీడర్‌బోర్డ్",
      recentAdventures: "ఇటీవలి సాహసాలు",
      weeklyPerformance: "వారపు పనితీరు",
      myBadgeCollection: "నా బ్యాడ్జ్ సేకరణ",
      myLearningGoals: "నా నేర్చుకునే లక్ష్యాలు",
      classChampions: "తరగతి ఛాంపియన్లు",
      attendance: "హాజరు",
      homework: "హోంవర్క్",
      behavior: "ప్రవర్తన",
      participation: "పాల్గొనడం",
      progress: "పురోగతి",
      completedMathHomework: "గణిత హోంవర్క్ పూర్తి చేసింది",
      perfectAttendance: "పరిపూర్ణ హాజరు",
      helpedClassmate: "తరగతి స్నేహితుడికి సహాయం చేసింది",
      perfectAttendanceBadge: "పరిపూర్ణ హాజరు",
      mathWizard: "గణిత మాంత్రికుడు",
      helperHero: "సహాయక హీరో",
      readBooks: "5 పుస్తకాలు చదవండి",
      improveHandwriting: "చేతివ్రాతను మెరుగుపరచండి",
    },
    ai: {
      studyBuddy: "AI అధ్యయన సహాయక",
      askQuestion: "మీ చదువు గురించి ఏదైనా అడగండి!",
      typing: "AI సహాయక ఆలోచిస్తోంది...",
      placeholder: "ఒక ప్రశ్న అడగండి...",
      sendMessage: "పంపండి",
    },
    schedule: {
      mySchedule: "నా షెడ్యూల్",
      monday: "సోమవారం",
      tuesday: "మంగళవారం",
      wednesday: "బుధవారం",
      thursday: "గురువారం",
      friday: "శుక్రవారం",
      saturday: "శనివారం",
      sunday: "ఆదివారం",
      time: "సమయం",
      subject: "విషయం",
      teacher: "ఉపాధ్యాయుడు",
      room: "గది",
    },
    materials: {
      studyMaterials: "అధ్యయన సామగ్రి",
      classNotes: "క్లాస్ నోట్‌లు",
      assignments: "కార్యనిర్దేశనాలు",
      referenceBooks: "సూచన పుస్తకాలు",
      uploadDate: "అప్‌లోడ్ తేదీ",
      downloadFile: "డౌన్‌లోడ్",
      previewFile: "ప్రివ్యూ",
      noMaterials: "ఇంకా సామగ్రి లేదు",
    },
  },
  bn: {
    common: {
      language: "ভাষা",
      logout: "লগ আউট",
      loading: "লোড হচ্ছে...",
      error: "ত্রুটি",
      success: "সফল",
      save: "সংরক্ষণ করুন",
      cancel: "বাতিল করুন",
      delete: "মুছে ফেলুন",
      edit: "সম্পাদনা করুন",
      add: "যোগ করুন",
      close: "বন্ধ করুন",
      back: "পিছনে",
    },
    navbar: {
      liveClasses: "লাইভ ক্লাস",
      schedule: "সময়সূচী",
      notes: "নোট",
      aiAssistant: "AI অধ্যয়ন সহায়ক",
      myLearning: "আমার শেখার অভিযান",
    },
    student: {
      dashboard: "শিক্ষার্থী ড্যাশবোর্ড",
      mySchedule: "আমার সময়সূচী",
      liveClasses: "লাইভ ক্লাস",
      notes: "অধ্যয়ন সামগ্রী",
      assignments: "অ্যাসাইনমেন্ট",
      joinClass: "ক্লাসে যোগ দিন",
      upcomingClasses: "আসন্ন ক্লাস",
      studyMaterials: "অধ্যয়ন সামগ্রী",
      classNotes: "ক্লাস নোট",
      referenceBooks: "রেফারেন্স বই",
      welcomeBack: "ফিরে স্বাগতম",
      levelStudent: "স্তর {level} শিক্ষার্থী",
      currentLevel: "বর্তমান স্তর",
      totalXP: "মোট XP",
      badgesEarned: "অর্জিত ব্যাজ",
      currentStreak: "বর্তমান স্ট্রীক",
      levelProgress: "স্তর অগ্রগতি",
      complete: "সম্পূর্ণ!",
      overview: "সংক্ষিপ্ত বিবরণ",
      badges: "ব্যাজ",
      goals: "লক্ষ্য",
      leaderboard: "লিডারবোর্ড",
      recentAdventures: "সাম্প্রতিক অভিযান",
      weeklyPerformance: "সাপ্তাহিক কর্মক্ষমতা",
      myBadgeCollection: "আমার ব্যাজ সংগ্রহ",
      myLearningGoals: "আমার শেখার লক্ষ্য",
      classChampions: "ক্লাস চ্যাম্পিয়ন",
      attendance: "উপস্থিতি",
      homework: "হোমওয়ার্ক",
      behavior: "আচরণ",
      participation: "অংশগ্রহণ",
      progress: "অগ্রগতি",
      completedMathHomework: "গণিত হোমওয়ার্ক সম্পন্ন",
      perfectAttendance: "নিখুঁত উপস্থিতি",
      helpedClassmate: "সহপাঠীকে সাহায্য করেছে",
      perfectAttendanceBadge: "নিখুঁত উপস্থিতি",
      mathWizard: "গণিত জাদুকর",
      helperHero: "সাহায্যকারী হিরো",
      readBooks: "৫টি বই পড়ুন",
      improveHandwriting: "হাতের লেখা উন্নত করুন",
    },
    ai: {
      studyBuddy: "AI অধ্যয়ন সহায়ক",
      askQuestion: "আপনার অধ্যয়ন সম্পর্কে যেকোনো প্রশ্ন করুন!",
      typing: "AI সহায়ক চিন্তা করছে...",
      placeholder: "একটি প্রশ্ন করুন...",
      sendMessage: "পাঠান",
    },
    schedule: {
      mySchedule: "আমার সময়সূচী",
      monday: "সোমবার",
      tuesday: "মঙ্গলবার",
      wednesday: "বুধবার",
      thursday: "বৃহস্পতিবার",
      friday: "শুক্রবার",
      saturday: "শনিবার",
      sunday: "রবিবার",
      time: "সময়",
      subject: "বিষয়",
      teacher: "শিক্ষক",
      room: "কক্ষ",
    },
    materials: {
      studyMaterials: "অধ্যয়ন সামগ্রী",
      classNotes: "ক্লাস নোট",
      assignments: "অ্যাসাইনমেন্ট",
      referenceBooks: "রেফারেন্স বই",
      uploadDate: "আপলোড তারিখ",
      downloadFile: "ডাউনলোড",
      previewFile: "প্রিভিউ",
      noMaterials: "এখনও কোনো সামগ্রী নেই",
    },
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const saved = localStorage.getItem("language") as Language | null
    if (saved && ["en", "hi", "ta", "te", "bn"].includes(saved)) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    const keys = key.split(".")
    let value: any = translations[language]

    for (const k of keys) {
      value = value?.[k]
    }

    return value || key
  }

  if (!mounted) {
    return <>{children}</>
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
